### ISSUE TITLE
Sometimes iot-rest-api-server@0.5.0 can't find resources

### ISSUE THREAD

**Issue by xiaoyu3x** [01org/iot-rest-api-server#75]
## Description:
Resources can't be find that happens 3/10 times when running '/bmi/temperature' sensors.

## Steps:
1.Install iot-rest-api-server to 0.5.0: npm install iot-rest-api-server@0.5.0 and launch it.
2.Build the temperature.js zjs-server JS sample and and flash it to set up the 6lowpan.
3.Try to discover the OCF resources: cd iot-rest-api-server/test && ./oic-get /res
4. Check port output information:
    `minicom -D /dev/ttyUSB0`

##Actual Result:
Sometimes iot-rest-api-server@0.5.0 can't find resources and port output:
![selection_004](https://user-images.githubusercontent.com/17694094/30199191-309d64f6-94a4-11e7-9122-0f087c576993.png)

## Expect Result:
iot-rest-api-server@0.5.0 can find resources all the time.

**Comment by nagineni** [comment]
This issue is not reproducible with the servers running on Linux. We probably see this only with ZJS OCF servers running on A101. The reason for the failure might be that there are no enough free buffers on ZJS device side to accommodate the response of the resource discovery. 

I guess we already have bugs reported in the ZJS about the size limitation.
